export const ridesData = [
  {
    id: 1,
    firstName: "Emmanuel",
    lastName: "Obiechina",
    email: "officialceo@mail.com",
    phoneNumber: "090276353422",
    program: "Uber",
    isCertified: false,
  },
  {
    id: 2,
    firstName: "David",
    lastName: "Dada",
    email: "david@mail.com",
    phoneNumber: "090276353422",
    program: "HatchDev",
    isCertified: true,
  },
  {
    id: 3,
    firstName: "Adedeji",
    lastName: "Tobiloba",
    email: "ade@mail.com",
    phoneNumber: "090276353422",
    program: "iot",
    isCertified: false,
  },
  {
    id: 4,
    firstName: "Fortune",
    lastName: "Dasilva",
    email: "thefutureX@mail.com",
    phoneNumber: "090276353422",
    program: "HatchDev",
    isCertified: false,
  },
  {
    id: 5,
    firstName: "Gregory",
    lastName: "Peter",
    email: "officialceo@mail.com",
    phoneNumber: "090276353422",
    program: "HatchDev",
    isCertified: true,
  },
  {
    id: 6,
    firstName: "Oluwaseun",
    lastName: "Adeshina",
    email: "seun@mail.com",
    phoneNumber: "090276353422",
    program: "Nitdev 2.1",
    isCertified: false,
  },
  {
    id: 7,
    firstName: "Oduyebo",
    lastName: "Oluwatobi",
    email: "tobi@mail.com",
    phoneNumber: "090276353422",
    program: "HatchDev",
    isCertified: true,
  },
];

export const tableHead = [
  "First Name",
  "Last Name",
  "Email",
  "Phone Number",
  "Acquired Certificate",
];
